### ISSUE TITLE
docker-compose fails

### ISSUE THREAD

**Issue by benblip** [truncj/thermos#2]
When I use **docker-compose up -d** I get:

ERROR: for 0500c116a4ac_prometheus  "host" network_mode is incompatible with port_bindings
ERROR: for grafana  "host" network_mode is incompatible with port_bindings
ERROR: for prometheus  "host" network_mode is incompatible with port_bindings

docker compose version 1.29.0

It seems you can't use network_mode = host when specifying ports?

**Comment by truncj** [comment]
Good catch. I've removed the ports for now as the services are currently using localhost to communicate. This should be externalized so you can run it either way.
