### ISSUE TITLE
docker-compose fails to start prometheus

### ISSUE THREAD

**Issue by benblip** [truncj/thermos#3]
When attempting to start on a rpi4, I get the following:
(I can see prometheus.yml appears as a directory, shouldn't it be a file?)

$docker-compose up -d

Starting thermos ... 
grafana is up-to-date
Starting prometheus ... 
Starting prometheus ... error

ERROR: for prometheus  Cannot start service prometheus: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:60: mounting "/home/pi/thermos/prometheus-config/prometheus.yml" to rootfs at "/var/lib/docker/overlay2/c3c864144053702b48098435fe3c50f064c01728deb2cf704a1770db6f2a81cd/merged/etc/prometheus/prometheus.yml" caused: not a directorStarting thermos    ... done
h exists and is the expected type

ERROR: for prometheus  Cannot start service prometheus: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:60: mounting "/home/pi/thermos/prometheus-config/prometheus.yml" to rootfs at "/var/lib/docker/overlay2/c3c864144053702b48098435fe3c50f064c01728deb2cf704a1770db6f2a81cd/merged/etc/prometheus/prometheus.yml" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by truncj** [comment]
Just added a default prometheus.yml, but you can customize this as needed

**Comment by benblip** [comment]
That's better. Thanks.
