### ISSUE TITLE
Containers are restarting due to errors. 

### ISSUE THREAD

**Issue by benblip** [truncj/thermos#4]
Still got a few things that need (re)configuration:
This was on a fresh Pi4

**pi@raspberrypi:~/thermos $ docker ps**
CONTAINER ID   IMAGE                           COMMAND                  CREATED         STATUS                          PORTS     NAMES
e8dc6cb2231a   ghcr.io/truncj/thermos:latest   "python -u main.py"      4 minutes ago   Restarting (1) 11 seconds ago             thermos
c4a98e66340a   grafana/grafana                 "/run.sh"                4 minutes ago   Restarting (1) 34 seconds ago             grafana
b7cf14bb5648   redis:6.0.12-alpine             "docker-entrypoint.s\u2026"   4 minutes ago   Up 4 minutes                              redis
d11ab7633163   prom/prometheus-linux-armv7     "/bin/prometheus --c\u2026"   4 minutes ago   Restarting (2) 33 seconds ago             prometheus

**pi@raspberrypi:~/thermos $ docker logs --follow thermos**
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from devices import Thermostat
  File "/app/devices.py", line 10, in <module>
    from w1thermsensor import W1ThermSensor, NoSensorFoundError
  File "/app/venv/lib/python3.7/site-packages/w1thermsensor/__init__.py", line 8, in <module>
    from .core import W1ThermSensor  # noqa
  File "/app/venv/lib/python3.7/site-packages/w1thermsensor/core.py", line 531, in <module>
    load_kernel_modules()
  File "/app/venv/lib/python3.7/site-packages/w1thermsensor/core.py", line 525, in load_kernel_modules
    raise KernelModuleLoadError()
w1thermsensor.errors.KernelModuleLoadError: Cannot load w1 therm kernel modules

**pi@raspberrypi:~/thermos $ docker logs --follow grafana**
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied

**pi@raspberrypi:~/thermos $ docker logs --follow prometheus**
level=info ts=2021-04-20T03:56:03.773Z caller=main.go:380 msg="No time or size retention was set so using the default time retention" duration=15d
level=info ts=2021-04-20T03:56:03.774Z caller=main.go:418 msg="Starting Prometheus" version="(version=2.26.0, branch=HEAD, revision=3cafc58827d1ebd1a67749f88be4218f0bab3d8d)"
level=warn ts=2021-04-20T03:56:03.774Z caller=main.go:420 msg="This Prometheus binary has not been compiled for a 64-bit architecture. Due to virtual memory constraints of 32-bit systems, it is highly recommended to switch to a 64-bit binary of Prometheus." GOARCH=arm
level=info ts=2021-04-20T03:56:03.774Z caller=main.go:423 build_context="(go=go1.16.2, user=root@978f8f2e1ea7, date=20210331-11:56:37)"
level=info ts=2021-04-20T03:56:03.774Z caller=main.go:424 host_details="(Linux 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l raspberrypi (none))"
level=info ts=2021-04-20T03:56:03.775Z caller=main.go:425 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2021-04-20T03:56:03.775Z caller=main.go:426 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2021-04-20T03:56:03.776Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log

**Comment by truncj** [comment]
Each one of these errors has a google-able solution. Give it a shot and let me know if you still have any issues.
